%%{init: {'theme':'forest'}}%%

sequenceDiagram

    Title Sequence diagram of .activate() of extension.ts

    participant p1 as activate
    participant src_mermaid-webview-panel_Mermaid-webview-panel as show<br>:mermaid-webview-panel


    p1 ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: show()
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- p1: 1: return value
    src_mermaid-webview-panel_Mermaid-webview-panel ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: _update(code)
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- src_mermaid-webview-panel_Mermaid-webview-panel: 2: return value
    src_mermaid-webview-panel_Mermaid-webview-panel ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: _getHtmlForWebview(code)
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- src_mermaid-webview-panel_Mermaid-webview-panel: 3: return value
    src_mermaid-webview-panel_Mermaid-webview-panel ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: MermaidWebviewPanel(panel, extensionUri, code)
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- src_mermaid-webview-panel_Mermaid-webview-panel: 4: return value
    src_mermaid-webview-panel_Mermaid-webview-panel ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: _update(code)
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- src_mermaid-webview-panel_Mermaid-webview-panel: 5: return value
    src_mermaid-webview-panel_Mermaid-webview-panel ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: jumpToFunction(funcName)
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- src_mermaid-webview-panel_Mermaid-webview-panel: 6: return value
    src_mermaid-webview-panel_Mermaid-webview-panel ->>+ src_mermaid-webview-panel_Mermaid-webview-panel: dispose()
    src_mermaid-webview-panel_Mermaid-webview-panel -->>- src_mermaid-webview-panel_Mermaid-webview-panel: 7: return value