name: Run VSCode Extension Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: code-reading-helper-by-mermaid-sequence-diagram

    - name: Find VS Code stable release version
      id: code-stable
      run: |
          echo "VSCODE_VERSION=`curl --silent https://update.code.visualstudio.com/api/releases/stable | jq -r '.[0]'`" >> "$GITHUB_OUTPUT"
      working-directory: code-reading-helper-by-mermaid-sequence-diagram
      
    - name: Cache VS Code download
      uses: actions/cache@v4
      with:
        path: |
            .vscode-test
        key: vscode-test-cache-${{ steps.code-stable.outputs.VSCODE_VERSION }}

    - name: Test using VS Code
        # commands before `xvfb-run -a npm run test` avoid these ERROR messages:
        # - Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
        # - Exiting GPU process due to errors during initialization
      run: |
          make unittest
      working-directory: code-reading-helper-by-mermaid-sequence-diagram

    # - name: Run tests
    #   run: xvfb-run -a npm test
    #   if: runner.os == 'Linux'
    #   working-directory: code-reading-helper-by-mermaid-sequence-diagram

    # - name: Run tests
    #   run: make unittest
    #   if: runner.os != 'Linux'
    #   working-directory: code-reading-helper-by-mermaid-sequence-diagram

    # - name: Run tests
    #   run: make unittest
      

    # - name: configure
    #   run: ./configure

    # - name: Install dependencies
    #   run: make

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
