name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make unittest

    # - name: configure
    #   run: ./configure

    # - name: Install dependencies
    #   run: make

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
