name: Run VSCode Extension Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Run tests
      run: make unittest
      if: runner.os != 'Linux'

    - name: Run tests
      run: make unittest
      working-directory: code-reading-helper-by-mermaid-sequence-diagram

    # - name: configure
    #   run: ./configure

    # - name: Install dependencies
    #   run: make

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
